vich_uploader:
    db_driver: orm
    mappings:
        proposal_pictures:
            uri_prefix: /images/proposal
            upload_destination: '%kernel.project_dir%/public/images/proposal%'
        


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
